### ISSUE TITLE
#P02. As Participant, I would like to reset my account password.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#19]

**Comment by AlexiaDelorme** [comment]
@AlexiaDelorme

**Comment by TravelTimN** [comment]
Thanks @AlexiaDelorme! You might discuss with @auxfuse who is working on some authentication.

**Comment by AlexiaDelorme** [comment]
Thanks! Sure will do!

**Comment by auxfuse** [comment]
Hi @AlexiaDelorme just touching base with you 😄 

I am hoping top have all the user auth stuff done by this weekend. Once done I'll ping you in this thread to let you know that the project can be then forked for your own issue participation 😄

**Comment by AlexiaDelorme** [comment]
@auxfuse Hey :) great, thanks a lot!

**Comment by auxfuse** [comment]
@AlexiaDelorme My issue is now done, you should be able to just `git pull upstream master` to get the lastest code base and then take it from there 😀

See PRs:

- #83
- #89

**Comment by AlexiaDelorme** [comment]
@auxfuse Brillant! 😁 Thanks for the update and congrats on completing your part! 🥳

**Comment by TravelTimN** [comment]
@AlexiaDelorme @auxfuse 
Just following-up on this one.
It looks like this one was taken care of with #83 is that correct?
Am I okay to go ahead and close this one now, in that case?

**Comment by AlexiaDelorme** [comment]
Well I think most of the all-auth templates to reset password were functional so I did not have much to do. Plus there was a separate issue to harmonize all the templates. I have just customized the password_change view so it returns to profile page instead of the form. But well... I have like 3 commits so it's not much but I can submit a PR.
