### ISSUE TITLE
#P05. As Participant, I would like to enroll for an upcoming Hackathon.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#22]

**Comment by mkuti** [comment]
@mkuti

**Comment by stefdworschak** [comment]
Thanks @mkuti! Moved it to "In Progress" on the projects board.

**Comment by stefdworschak** [comment]
@mkuti no pressure, just checking if you are still working on this or should we move it back to "To Do"?

**Comment by stefdworschak** [comment]
@mkuti could you please come back on this issue? If you are not working on it I will move it back to "To Do".

**Comment by mkuti** [comment]
Hi Stefan, sorry for the late reply and for not participating in the
project much since the beginning.
If it's too late, you could put it back in the 'to do' list. If not I have
started a little and was waiting for the list of the hackatons to be added
before I could finalise it.
Sorry for not communicating enough, I am not online enough lately, but kept
checking for latest updates.
I can work more tonight.
Thank you.
Maripia
