### ISSUE TITLE
#P07. As Participant, I would like to view my team's information.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#24]
Visible items should only include:
- Team Name
- Slack Display Names of Members

**Comment by AMcCall22** [comment]
@AMcCall22 please :)

**Comment by TravelTimN** [comment]
@AMcCall22 
I'm just checking-in with this issue, since it's still "Open".
How are you and @stephy getting on with progress, or has this been sorted via a different PR now?

**Comment by AMcCall22** [comment]
Hi Tim, I have arranged with Stephy to take the PR on from here as we were going to combine them. Apologies  I wasn’t able to complete (did make a start and passed on the detail to her. I also let Stefan know) but I have to focus on my MS4 at the moment... Ali Sent from Mail for Windows 10 From: Tim NelsonSent: 09 November 2020 13:02To: Code-Institute-Community/ci-hackathon-appCc: AMcCall22; MentionSubject: Re: [Code-Institute-Community/ci-hackathon-app] #P07. As Participant, I would like to view my team's information. (#24) @AMcCall22I'm just checking-in with this issue, since it's still "Open".How are you and @stephy getting on with progress, or has this been sorted via a different PR now?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
